DROP TABLE IF EXISTS `character_stats`;
CREATE TABLE IF NOT EXISTS `character_stats` (
  `guid` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Global Unique Identifier, Low part',
  `maxhealth` int(10) unsigned NOT NULL DEFAULT '0',
  `maxpower1` int(10) unsigned NOT NULL DEFAULT '0',
  `maxpower2` int(10) unsigned NOT NULL DEFAULT '0',
  `maxpower3` int(10) unsigned NOT NULL DEFAULT '0',
  `maxpower4` int(10) unsigned NOT NULL DEFAULT '0',
  `maxpower5` int(10) unsigned NOT NULL DEFAULT '0',
  `maxpower6` int(10) unsigned NOT NULL DEFAULT '0',
  `maxpower7` int(10) unsigned NOT NULL DEFAULT '0',
  `strength` int(10) unsigned NOT NULL DEFAULT '0',
  `agility` int(10) unsigned NOT NULL DEFAULT '0',
  `stamina` int(10) unsigned NOT NULL DEFAULT '0',
  `intellect` int(10) unsigned NOT NULL DEFAULT '0',
  `spirit` int(10) unsigned NOT NULL DEFAULT '0',
  `armor` int(10) unsigned NOT NULL DEFAULT '0',
  `resHoly` int(10) unsigned NOT NULL DEFAULT '0',
  `resFire` int(10) unsigned NOT NULL DEFAULT '0',
  `resNature` int(10) unsigned NOT NULL DEFAULT '0',
  `resFrost` int(10) unsigned NOT NULL DEFAULT '0',
  `resShadow` int(10) unsigned NOT NULL DEFAULT '0',
  `resArcane` int(10) unsigned NOT NULL DEFAULT '0',
  `blockPct` float unsigned NOT NULL DEFAULT '0',
  `dodgePct` float unsigned NOT NULL DEFAULT '0',
  `parryPct` float unsigned NOT NULL DEFAULT '0',
  `critPct` float unsigned NOT NULL DEFAULT '0',
  `rangedCritPct` float unsigned NOT NULL DEFAULT '0',
  `spellCritPct` float unsigned NOT NULL DEFAULT '0',
  `attackPower` int(10) unsigned NOT NULL DEFAULT '0',
  `rangedAttackPower` int(10) unsigned NOT NULL DEFAULT '0',
  `spellPower` int(10) unsigned NOT NULL DEFAULT '0',
  `a_apmelee` int(11) NOT NULL,
  `a_ranged` int(11) NOT NULL,
  `a_blockrating` int(11) NOT NULL,
  `a_defrating` int(11) NOT NULL,
  `a_dodgerating` int(11) NOT NULL,
  `a_parryrating` int(11) NOT NULL,
  `a_resilience` int(11) NOT NULL,
  `a_manaregen` float NOT NULL,
  `a_melee_hitrating` int(11) NOT NULL,
  `a_melee_critrating` int(11) NOT NULL,
  `a_melee_hasterating` int(11) NOT NULL,
  `a_melee_mainmindmg` float NOT NULL,
  `a_melee_mainmaxdmg` float NOT NULL,
  `a_melee_offmindmg` float NOT NULL,
  `a_melee_offmaxdmg` float NOT NULL,
  `a_melee_maintime` float NOT NULL,
  `a_melee_offtime` float NOT NULL,
  `a_ranged_critrating` int(11) NOT NULL,
  `a_ranged_hasterating` int(11) NOT NULL,
  `a_ranged_hitrating` int(11) NOT NULL,
  `a_ranged_mindmg` float NOT NULL,
  `a_ranged_maxdmg` float NOT NULL,
  `a_ranged_attacktime` float NOT NULL,
  `a_spell_hitrating` int(11) NOT NULL,
  `a_spell_critrating` int(11) NOT NULL,
  `a_spell_hasterating` int(11) NOT NULL,
  `a_spell_bonusdmg` int(11) NOT NULL,
  `a_spell_bonusheal` int(11) NOT NULL,
  `a_spell_critproc` float NOT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
